import { test, expect, type WebSocketRoute } from '@playwright/test';

test('two friends share a table, complete a turn, and resume after reload', async ({ browser, page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByLabel('Your commander name').fill('Ada');
  await page.getByRole('button', { name: 'Create your table' }).click();
  const code = await page.getByTestId('room-code').textContent();
  const context = await browser.newContext();
  const friend = await context.newPage();
  friend.on('pageerror', error => errors.push(error.message));
  await friend.goto(`/?room=${code}`);
  await friend.getByLabel('Your commander name').fill('Grace');
  await friend.getByRole('button', { name: 'Join the table' }).click();
  await expect(friend.getByText('Waiting for the host')).toBeVisible();
  await expect(page.getByText('Grace', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Begin World Domination' }).click();
  await expect(page.getByTestId('phase')).toHaveText('Draft');
  await expect(friend.getByTestId('phase')).toHaveText('Draft');
  await expect(page.getByTestId('world-board')).toHaveAttribute('data-ready', 'true');
  await page.getByRole('button', { name: 'Territory list' }).click();
  const owned = page.locator('[data-testid^="territory-"][data-owner="0"]').first();
  await owned.click();
  await page.getByRole('button', { name: /Deploy .* troops/ }).click();
  await expect(page.getByTestId('phase')).toHaveText('Attack');
  await expect(friend.getByTestId('phase')).toHaveText('Attack');
  await page.getByRole('button', { name: 'Finish attacking' }).click();
  await page.getByRole('button', { name: 'Skip fortify · end turn' }).click();
  await expect(friend.getByTestId('turn-status')).toHaveText('YOUR TURN');
  await friend.reload();
  await expect(friend.getByTestId('phase')).toHaveText('Draft');
  await expect(friend.getByTestId('turn-status')).toHaveText('YOUR TURN');
  await friend.getByRole('button', { name: 'Territory list' }).click();
  await friend.locator('[data-testid^="territory-"][data-owner="1"]').first().click();
  await friend.getByRole('button', { name: /Deploy .* troops/ }).click();
  await expect(page.getByTestId('phase')).toHaveText('Attack');
  expect(errors).toEqual([]);
  await context.close();
});

test('host configures mixed AI seats and bots advance the campaign', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Your commander name').fill('Commander');
  await page.getByRole('button', { name: 'Create your table' }).click();
  await page.getByLabel('AI difficulty').selectOption('easy');
  await page.getByRole('button', { name: 'Add AI player' }).click();
  await page.getByLabel('AI difficulty').selectOption('hard');
  await page.getByRole('button', { name: 'Add AI player' }).click();
  await expect(page.getByText('Easy AI 2')).toBeVisible();
  await expect(page.getByText('Hard AI 3')).toBeVisible();
  await page.getByRole('button', { name: 'Begin World Domination' }).click();
  await page.getByRole('button', { name: 'Territory list' }).click();
  await page.locator('[data-testid^="territory-"][data-owner="0"]').first().click();
  await page.getByRole('button', { name: /Deploy .* troops/ }).click();
  await page.getByRole('button', { name: 'Finish attacking' }).click();
  await page.getByRole('button', { name: 'Skip fortify · end turn' }).click();
  await expect(page.getByTestId('turn-status')).toHaveText('AI IS THINKING');
  await expect(page.getByTestId('turn-status')).toHaveText('YOUR TURN', { timeout: 40_000 });
  await expect(page.getByTestId('phase')).toHaveText('Draft');
});

test('phone layout supports lobby setup without horizontal scrolling', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(crypto, 'randomUUID', { value: undefined }));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByLabel('Your commander name').fill('Mobile');
  await page.getByRole('button', { name: 'Create your table' }).click();
  await page.getByRole('button', { name: 'Add AI player' }).click();
  await page.getByRole('button', { name: 'Begin World Domination' }).click();
  await page.getByRole('button', { name: 'Territory list' }).click();
  await page.locator('[data-testid^="territory-"][data-owner="0"]').first().click();
  await page.getByRole('button', { name: /Deploy .* troops/ }).click();
  await expect(page.getByTestId('phase')).toHaveText('Attack');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('offline leave preserves the only seat credential until the server is reachable', async ({ browser, page }) => {
  test.setTimeout(90_000);
  let socket: WebSocketRoute | undefined;
  await page.context().routeWebSocket('**/play**', route => { socket = route; route.connectToServer(); });
  await page.goto('/');
  await page.getByLabel('Your commander name').fill('Reconnect host');
  await page.getByRole('button', { name: 'Create your table' }).click();
  const code = await page.getByTestId('room-code').textContent();
  const friendContext = await browser.newContext();
  const friend = await friendContext.newPage();
  await friend.goto(`/?room=${code}`);
  await friend.getByLabel('Your commander name').fill('Waiting friend');
  await friend.getByRole('button', { name: 'Join the table' }).click();
  await expect(page.getByText('Waiting friend', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Begin World Domination' }).click();
  await expect(page.getByTestId('phase')).toHaveText('Draft');
  const saved = await page.evaluate(() => sessionStorage.getItem('risk-game-seat'));
  await page.context().setOffline(true);
  socket!.close({ code: 1011, reason: 'Simulated connection loss' });
  await page.getByRole('button', { name: 'Return home' }).waitFor({ timeout: 35_000 });
  await page.getByRole('button', { name: 'Return home' }).click();
  await expect(page.getByRole('button', { name: 'Reconnect', exact: true })).toBeVisible();
  expect(await page.evaluate(() => sessionStorage.getItem('risk-game-seat'))).toBe(saved);
  await page.context().setOffline(false);
  await page.getByRole('button', { name: 'Reconnect', exact: true }).click();
  await expect(page.getByTestId('turn-status')).toHaveText('YOUR TURN');
  await page.getByRole('button', { name: 'Territory list' }).click();
  await page.locator('[data-testid^="territory-"][data-owner="0"]').first().click();
  await page.getByRole('button', { name: /Deploy .* troops/ }).click();
  await expect(friend.getByTestId('phase')).toHaveText('Attack');
  await friendContext.close();
});
